#!/usr/bin/env bash

cwd=$(pwd)
build=$cwd/build

if [ -d "$build" ]; then
  rm -rf $build
fi

mkdir $build
mkdir $build/dist
mkdir $build/plugin
mkdir $build/plugin/EmailProtect

yarn build

cp -r "$cwd/dist/"* "$build/dist/"
cp "$cwd/composer.json" "$build/"
cp "$cwd/composer.lock" "$build/"
cp "$cwd/rector.php" "$build/"
cp "$cwd/LICENSE" "$build/"
cp "$cwd/email-protect.php" "$build/"
cp "$cwd/readme.txt" "$build/"
cp -r "$cwd/plugin/EmailProtect/"* "$build/plugin/EmailProtect"

cd "$build"

composer install
./vendor/bin/rector process
sed -i "s/Requires PHP: 8.1/Requires PHP: 7.1/" email-protect.php
sed -i "s/\"php\": \">=8.1\"/\"php\": \">=7.1\"/" composer.json
composer update

sleep 1

rm -rf vendor/
rm -f rector.php

composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader --prefer-dist

zip -qqr "$cwd/email-protect.zip" .

rm -rf $build