name: Deploy to development server

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache composer package
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Cache node modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader --prefer-dist

      - name: Install yarn dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build scripts
        run: yarn build

      - name: Transpile to php7.0
        uses: zingimmick/rector-action@0.0.2
        with:
          args: --dry-run

      - name: Sync to development server
        env:
          dest: '${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/vhosts/code-leaf.de/development.code-leaf.de/wp-content/plugins/mail-protect'
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.wordpress/ \
            --exclude /node_modules/ \
            --exclude /src/ \
            --exclude /tests/ \
            --exclude /.babelrc \
            --exclude /.gitignore \
            --exclude /build_plugin \
            --exclude /package.json \
            --exclude /phpstan.neon \
            --exclude /tsconfig.json \
            --exclude /webpack.config.js \
            ./ ${{ env.dest }}